// ============================================================
// BASE DE ALIMENTOS COMPLETA - NUTRIÇÃO CLÍNICA E ESPORTIVA
// Dados baseados em TACO (Tabela Brasileira de Composição de Alimentos),
// IBGE e referências de nutricionistas esportivos.
// Valores por 100g ou 100ml do alimento (cozido/preparado conforme descrito).
// Imagens: Unsplash (uso livre, sem necessidade de atribuição obrigatória)
// ============================================================

export const categorias = {
    PROTEINAS_ANIMAIS: "Proteínas Animais",
    OVOS: "Ovos",
    LATICINIOS: "Laticínios",
    LEGUMINOSAS: "Leguminosas",
    PROTEINAS_VEGETAIS: "Proteínas Vegetais",
    CARBO_COMPLEXOS: "Carboidratos Complexos",
    TUBERCULOS: "Tubérculos e Raízes",
    FRUTAS: "Frutas",
    LEGUMES_VERDURAS: "Legumes e Verduras",
    GORDURAS_BOAS: "Gorduras Saudáveis",
    OLEAGINOSAS: "Oleaginosas e Sementes",
    SUPLEMENTOS: "Suplementos",
    BEBIDAS: "Bebidas",
    TEMPEROS: "Temperos e Condimentos",
};

export const objetivos = {
    EMAGRECIMENTO: "emagrecimento",
    GANHO_MASSA: "ganho_massa",
    MANUTENCAO: "manutencao",
    DEFINICAO: "definicao",
    SAUDE_GERAL: "saude_geral",
};

// Índice de saciedade: "baixo" | "medio" | "alto" | "muito_alto"
// Índice glicêmico:    "baixo" (<55) | "medio" (55-70) | "alto" (>70)

// ============================================================
// PROTEÍNAS ANIMAIS
// ============================================================
const proteinasAnimais = [
    {
        id: "pa_001",
        nome: "Peito de Frango Grelhado",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400&q=80",
        calorias_100g: 165,
        proteinas_100g: 31.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 3.6,
        fibras_100g: 0.0,
        sodio_100g: 74,
        porcao_comum_g: 150,
        unidade_medida: "g",
        descricao: "Grelhado sem pele, sem adição de gordura",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Principal proteína magra da dieta brasileira. Rico em B3 e selênio.",
    },
    {
        id: "pa_002",
        nome: "Peito de Frango Cru",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&q=80",
        calorias_100g: 109,
        proteinas_100g: 23.3,
        carboidratos_100g: 0.0,
        gorduras_100g: 1.5,
        fibras_100g: 0.0,
        sodio_100g: 58,
        porcao_comum_g: 180,
        unidade_medida: "g",
        descricao: "Cru sem pele — referência para pesar antes do cozimento",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Pese sempre cru para maior precisão calórica.",
    },
    {
        id: "pa_003",
        nome: "Frango Coxa e Sobrecoxa (sem pele, cozido)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80",
        calorias_100g: 190,
        proteinas_100g: 27.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 9.0,
        fibras_100g: 0.0,
        sodio_100g: 89,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Cozido sem pele",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "alto",
        observacoes: "Mais saboroso que o peito e mais rico em zinco e ferro.",
    },
    {
        id: "pa_004",
        nome: "Patinho Bovino (bife grelhado)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=400&q=80",
        calorias_100g: 153,
        proteinas_100g: 29.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 4.0,
        fibras_100g: 0.0,
        sodio_100g: 65,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Corte bovino magro grelhado sem gordura",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Um dos cortes bovinos mais magros. Rico em ferro heme e creatina natural.",
    },
    {
        id: "pa_005",
        nome: "Carne Moída Patinho (cozida)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&q=80",
        calorias_100g: 219,
        proteinas_100g: 35.9,
        carboidratos_100g: 0.0,
        gorduras_100g: 7.3,
        fibras_100g: 0.0,
        sodio_100g: 80,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Patinho moído cozido sem gordura adicional",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.DEFINICAO, objetivos.MANUTENCAO],
        indice_saciedade: "alto",
        observacoes: "Alta densidade proteica e versatilidade para diversas preparações.",
    },
    {
        id: "pa_006",
        nome: "Alcatra (grelhada)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&q=80",
        calorias_100g: 205,
        proteinas_100g: 28.5,
        carboidratos_100g: 0.0,
        gorduras_100g: 10.0,
        fibras_100g: 0.0,
        sodio_100g: 70,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Grelhada sem adição de gordura",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "alto",
        observacoes: "Rico em creatina natural, zinco e vitamina B12.",
    },
    {
        id: "pa_007",
        nome: "Filé de Tilápia (grelhado)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80",
        calorias_100g: 128,
        proteinas_100g: 26.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 2.7,
        fibras_100g: 0.0,
        sodio_100g: 52,
        porcao_comum_g: 150,
        unidade_medida: "g",
        descricao: "Grelhado sem gordura adicionada",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Peixe de baixo custo com excelente perfil proteico e gordura baixíssima.",
    },
    {
        id: "pa_008",
        nome: "Salmão (grelhado)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&q=80",
        calorias_100g: 208,
        proteinas_100g: 28.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 10.5,
        fibras_100g: 0.0,
        sodio_100g: 59,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Grelhado sem pele",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Excelente fonte de ômega-3 (EPA+DHA). Potente anti-inflamatório.",
    },
    {
        id: "pa_009",
        nome: "Atum em Conserva (ao natural)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1635863138275-d9864d46bae3?w=400&q=80",
        calorias_100g: 130,
        proteinas_100g: 29.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 1.5,
        fibras_100g: 0.0,
        sodio_100g: 310,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Conserva em água, bem escorrida",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Proteína de alta disponibilidade e praticidade. Atenção ao sódio.",
    },
    {
        id: "pa_010",
        nome: "Sardinha em Conserva (ao natural)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1556269923-e4ef51d69638?w=400&q=80",
        calorias_100g: 185,
        proteinas_100g: 25.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 9.5,
        fibras_100g: 0.0,
        sodio_100g: 400,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Conserva em água",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.GANHO_MASSA],
        indice_saciedade: "alto",
        observacoes: "Rica em ômega-3 e cálcio (quando consumida com espinhas).",
    },
    {
        id: "pa_011",
        nome: "Camarão Cozido",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&q=80",
        calorias_100g: 99,
        proteinas_100g: 21.0,
        carboidratos_100g: 0.9,
        gorduras_100g: 1.1,
        fibras_100g: 0.0,
        sodio_100g: 224,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Cozido, sem casca",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Proteína magra, rico em selênio e iodo.",
    },
    {
        id: "pa_012",
        nome: "Peru Peito (grelhado)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=400&q=80",
        calorias_100g: 135,
        proteinas_100g: 29.9,
        carboidratos_100g: 0.0,
        gorduras_100g: 1.8,
        fibras_100g: 0.0,
        sodio_100g: 63,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Peito de peru sem pele grelhado",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Proteína ainda mais magra que o peito de frango.",
    },
    {
        id: "pa_013",
        nome: "Filé de Merluza (cozido)",
        marca: "Geral",
        categoria: categorias.PROTEINAS_ANIMAIS,
        imagem: "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=400&q=80",
        calorias_100g: 90,
        proteinas_100g: 18.8,
        carboidratos_100g: 0.0,
        gorduras_100g: 1.4,
        fibras_100g: 0.0,
        sodio_100g: 70,
        porcao_comum_g: 150,
        unidade_medida: "g",
        descricao: "Filé cozido no vapor ou grelhado",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Peixe muito magro e acessível. Ótimo para dietas hipocalóricas.",
    },
];

// ============================================================
// OVOS
// ============================================================
const ovos = [
    {
        id: "ov_001",
        nome: "Ovo de Galinha Inteiro (cozido)",
        marca: "Geral",
        categoria: categorias.OVOS,
        imagem: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&q=80",
        calorias_100g: 155,
        proteinas_100g: 13.3,
        carboidratos_100g: 1.1,
        gorduras_100g: 10.6,
        fibras_100g: 0.0,
        sodio_100g: 124,
        porcao_comum_g: 60,
        unidade_medida: "unidade",
        peso_unidade_g: 60,
        descricao: "Ovo médio cozido inteiro",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO, objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "Proteína de maior valor biológico existente. Rica em colina, luteína e vitamina D.",
    },
    {
        id: "ov_002",
        nome: "Clara de Ovo (cozida)",
        marca: "Geral",
        categoria: categorias.OVOS,
        imagem: "https://images.unsplash.com/photo-1607621048318-33d5e6cd7f23?w=400&q=80",
        calorias_100g: 52,
        proteinas_100g: 11.0,
        carboidratos_100g: 0.7,
        gorduras_100g: 0.2,
        fibras_100g: 0.0,
        sodio_100g: 166,
        porcao_comum_g: 33,
        unidade_medida: "unidade",
        peso_unidade_g: 33,
        descricao: "Apenas a clara, cozida (≈33g/unidade)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Proteína quase pura com praticamente nenhuma gordura.",
    },
    {
        id: "ov_003",
        nome: "Ovo Mexido (sem gordura)",
        marca: "Geral",
        categoria: categorias.OVOS,
        imagem: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400&q=80",
        calorias_100g: 148,
        proteinas_100g: 10.0,
        carboidratos_100g: 1.6,
        gorduras_100g: 11.0,
        fibras_100g: 0.0,
        sodio_100g: 144,
        porcao_comum_g: 120,
        unidade_medida: "g",
        descricao: "Ovos mexidos sem adição de óleo ou manteiga",
        objetivos_recomendados: [objetivos.MANUTENCAO, objetivos.GANHO_MASSA],
        indice_saciedade: "alto",
        observacoes: "Prepare em panela antiaderente sem gordura.",
    },
    {
        id: "ov_004",
        nome: "Omelete Simples",
        marca: "Geral",
        categoria: categorias.OVOS,
        imagem: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80",
        calorias_100g: 154,
        proteinas_100g: 10.6,
        carboidratos_100g: 0.5,
        gorduras_100g: 11.9,
        fibras_100g: 0.0,
        sodio_100g: 230,
        porcao_comum_g: 110,
        unidade_medida: "g",
        descricao: "Omelete com 2 ovos médios sem recheio",
        objetivos_recomendados: [objetivos.MANUTENCAO, objetivos.GANHO_MASSA, objetivos.EMAGRECIMENTO],
        indice_saciedade: "alto",
        observacoes: "Adicione legumes para aumentar volume e fibras sem grandes calorias.",
    },
];

// ============================================================
// LATICÍNIOS
// ============================================================
const laticinios = [
    {
        id: "lt_001",
        nome: "Iogurte Grego Integral (sem açúcar)",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",
        calorias_100g: 97,
        proteinas_100g: 9.0,
        carboidratos_100g: 3.6,
        gorduras_100g: 5.0,
        fibras_100g: 0.0,
        sodio_100g: 36,
        porcao_comum_g: 170,
        unidade_medida: "g",
        descricao: "Iogurte grego natural, sem açúcar adicionado",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Excelente fonte de proteína e probióticos. Sempre preferir versão sem açúcar.",
    },
    {
        id: "lt_002",
        nome: "Iogurte Natural Desnatado",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400&q=80",
        calorias_100g: 47,
        proteinas_100g: 4.1,
        carboidratos_100g: 6.0,
        gorduras_100g: 0.5,
        fibras_100g: 0.0,
        sodio_100g: 52,
        porcao_comum_g: 170,
        unidade_medida: "g",
        descricao: "Iogurte natural desnatado sem açúcar",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Baixo calórico e boa fonte de cálcio e probióticos.",
    },
    {
        id: "lt_003",
        nome: "Queijo Cottage",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1601933573990-4b7c8ef3e3df?w=400&q=80",
        calorias_100g: 98,
        proteinas_100g: 11.1,
        carboidratos_100g: 3.4,
        gorduras_100g: 4.3,
        fibras_100g: 0.0,
        sodio_100g: 364,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Queijo fresco de baixo teor de gordura",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Um dos queijos mais indicados em dietas. Rico em caseína.",
    },
    {
        id: "lt_004",
        nome: "Queijo Ricota Fresca",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80",
        calorias_100g: 134,
        proteinas_100g: 9.8,
        carboidratos_100g: 3.0,
        gorduras_100g: 8.8,
        fibras_100g: 0.0,
        sodio_100g: 84,
        porcao_comum_g: 50,
        unidade_medida: "g",
        descricao: "Ricota fresca",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Baixo sódio, versátil. Boa fonte de cálcio.",
    },
    {
        id: "lt_005",
        nome: "Queijo Mussarela",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=400&q=80",
        calorias_100g: 300,
        proteinas_100g: 22.0,
        carboidratos_100g: 2.2,
        gorduras_100g: 22.0,
        fibras_100g: 0.0,
        sodio_100g: 627,
        porcao_comum_g: 30,
        unidade_medida: "fatia",
        peso_unidade_g: 30,
        descricao: "Mussarela convencional fatiada",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Usar com moderação. Alto sódio e gordura saturada.",
    },
    {
        id: "lt_006",
        nome: "Coalhada Seca",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=400&q=80",
        calorias_100g: 68,
        proteinas_100g: 10.3,
        carboidratos_100g: 3.4,
        gorduras_100g: 0.9,
        fibras_100g: 0.0,
        sodio_100g: 40,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Coalhada seca caseira ou industrializada",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Muito proteica e baixíssima gordura. Excelente alternativa ao iogurte grego.",
    },
    {
        id: "lt_007",
        nome: "Leite Desnatado",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
        calorias_100g: 34,
        proteinas_100g: 3.4,
        carboidratos_100g: 4.9,
        gorduras_100g: 0.1,
        fibras_100g: 0.0,
        sodio_100g: 50,
        porcao_comum_g: 200,
        unidade_medida: "ml",
        descricao: "Leite UHT desnatado",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "baixo",
        observacoes: "Baixo calórico, mantém cálcio e proteínas do leite integral.",
    },
    {
        id: "lt_008",
        nome: "Leite Integral",
        marca: "Geral",
        categoria: categorias.LATICINIOS,
        imagem: "https://images.unsplash.com/photo-1600718374662-0483d2b9da44?w=400&q=80",
        calorias_100g: 61,
        proteinas_100g: 3.2,
        carboidratos_100g: 4.8,
        gorduras_100g: 3.2,
        fibras_100g: 0.0,
        sodio_100g: 47,
        porcao_comum_g: 200,
        unidade_medida: "ml",
        descricao: "Leite UHT integral",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Boa fonte de cálcio, fósforo e vitamina D.",
    },
];

// ============================================================
// CARBOIDRATOS COMPLEXOS E TUBÉRCULOS
// ============================================================
const carboidratosComplexos = [
    {
        id: "cc_001",
        nome: "Arroz Branco Cozido",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
        calorias_100g: 130,
        proteinas_100g: 2.7,
        carboidratos_100g: 28.1,
        gorduras_100g: 0.3,
        fibras_100g: 0.4,
        sodio_100g: 1,
        porcao_comum_g: 150,
        unidade_medida: "g",
        indice_glicemico: "alto",
        descricao: "Arroz branco polido cozido",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Principal fonte de carboidrato da dieta brasileira. Ótimo no pós-treino.",
    },
    {
        id: "cc_002",
        nome: "Arroz Integral Cozido",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400&q=80",
        calorias_100g: 124,
        proteinas_100g: 2.6,
        carboidratos_100g: 25.8,
        gorduras_100g: 1.0,
        fibras_100g: 1.8,
        sodio_100g: 4,
        porcao_comum_g: 150,
        unidade_medida: "g",
        indice_glicemico: "medio",
        descricao: "Arroz integral cozido",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Maior teor de fibras, magnésio e vitaminas B. Menor IG que o arroz branco.",
    },
    {
        id: "cc_003",
        nome: "Batata-Doce Cozida",
        marca: "Geral",
        categoria: categorias.TUBERCULOS,
        imagem: "https://images.unsplash.com/photo-1596097893408-9db1e5c5d27a?w=400&q=80",
        calorias_100g: 86,
        proteinas_100g: 1.6,
        carboidratos_100g: 20.1,
        gorduras_100g: 0.1,
        fibras_100g: 2.2,
        sodio_100g: 27,
        porcao_comum_g: 150,
        unidade_medida: "g",
        indice_glicemico: "medio",
        descricao: "Cozida com ou sem casca",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.GANHO_MASSA, objetivos.DEFINICAO, objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "Alimento favorito de atletas. Rica em betacaroteno, potássio e vitamina C.",
    },
    {
        id: "cc_004",
        nome: "Aveia em Flocos Grossos",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=400&q=80",
        calorias_100g: 394,
        proteinas_100g: 13.9,
        carboidratos_100g: 66.6,
        gorduras_100g: 8.5,
        fibras_100g: 9.1,
        sodio_100g: 5,
        porcao_comum_g: 40,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Aveia em flocos grossos crua",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.GANHO_MASSA],
        indice_saciedade: "muito_alto",
        observacoes: "Rica em beta-glucana: reduz colesterol LDL e melhora sensibilidade à insulina.",
    },
    {
        id: "cc_005",
        nome: "Macarrão Integral Cozido",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80",
        calorias_100g: 149,
        proteinas_100g: 5.3,
        carboidratos_100g: 29.0,
        gorduras_100g: 1.0,
        fibras_100g: 3.0,
        sodio_100g: 2,
        porcao_comum_g: 180,
        unidade_medida: "g",
        indice_glicemico: "medio",
        descricao: "Macarrão integral cozido al dente",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.MANUTENCAO],
        indice_saciedade: "alto",
        observacoes: "Mais fibras e menor IG que o macarrão branco.",
    },
    {
        id: "cc_006",
        nome: "Macarrão de Sêmola Cozido",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=400&q=80",
        calorias_100g: 158,
        proteinas_100g: 5.8,
        carboidratos_100g: 30.9,
        gorduras_100g: 0.9,
        fibras_100g: 1.2,
        sodio_100g: 2,
        porcao_comum_g: 180,
        unidade_medida: "g",
        indice_glicemico: "alto",
        descricao: "Macarrão branco cozido",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Boa fonte de energia rápida para treinos de alta intensidade.",
    },
    {
        id: "cc_007",
        nome: "Quinoa Cozida",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400&q=80",
        calorias_100g: 120,
        proteinas_100g: 4.4,
        carboidratos_100g: 21.3,
        gorduras_100g: 1.9,
        fibras_100g: 2.8,
        sodio_100g: 7,
        porcao_comum_g: 130,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Quinoa cozida em água",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "Pseudocereal com proteína completa (todos aminoácidos essenciais). Sem glúten.",
    },
    {
        id: "cc_008",
        nome: "Pão Integral",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
        calorias_100g: 250,
        proteinas_100g: 9.4,
        carboidratos_100g: 46.0,
        gorduras_100g: 3.9,
        fibras_100g: 6.0,
        sodio_100g: 470,
        porcao_comum_g: 30,
        unidade_medida: "fatia",
        peso_unidade_g: 30,
        indice_glicemico: "medio",
        descricao: "Pão de forma integral (1 fatia = 30g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Verificar rótulo: o primeiro ingrediente deve ser farinha integral.",
    },
    {
        id: "cc_009",
        nome: "Pão Francês",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1549931319-a545dcf3bc7c?w=400&q=80",
        calorias_100g: 300,
        proteinas_100g: 9.0,
        carboidratos_100g: 58.0,
        gorduras_100g: 3.3,
        fibras_100g: 2.3,
        sodio_100g: 615,
        porcao_comum_g: 50,
        unidade_medida: "unidade",
        peso_unidade_g: 50,
        indice_glicemico: "alto",
        descricao: "Pão francês (1 unidade ≈ 50g)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Alto sódio. Consumir com proteína para reduzir o IG da refeição.",
    },
    {
        id: "cc_010",
        nome: "Tapioca (goma hidratada)",
        marca: "Geral",
        categoria: categorias.CARBO_COMPLEXOS,
        imagem: "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=400&q=80",
        calorias_100g: 243,
        proteinas_100g: 0.2,
        carboidratos_100g: 60.0,
        gorduras_100g: 0.0,
        fibras_100g: 0.0,
        sodio_100g: 4,
        porcao_comum_g: 70,
        unidade_medida: "g",
        indice_glicemico: "alto",
        descricao: "Beiju de tapioca (1 unidade ≈ 70g de goma)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "baixo",
        observacoes: "Sem glúten. Recheie com proteína magra para equilibrar o IG.",
    },
    {
        id: "cc_011",
        nome: "Batata Inglesa Cozida",
        marca: "Geral",
        categoria: categorias.TUBERCULOS,
        imagem: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80",
        calorias_100g: 87,
        proteinas_100g: 1.9,
        carboidratos_100g: 19.6,
        gorduras_100g: 0.1,
        fibras_100g: 1.5,
        sodio_100g: 6,
        porcao_comum_g: 150,
        unidade_medida: "g",
        indice_glicemico: "alto",
        descricao: "Batata cozida com casca",
        objetivos_recomendados: [objetivos.MANUTENCAO, objetivos.GANHO_MASSA],
        indice_saciedade: "alto",
        observacoes: "Um dos alimentos de maior índice de saciedade. Rica em potássio.",
    },
    {
        id: "cc_012",
        nome: "Inhame Cozido",
        marca: "Geral",
        categoria: categorias.TUBERCULOS,
        imagem: "https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=400&q=80",
        calorias_100g: 116,
        proteinas_100g: 1.5,
        carboidratos_100g: 27.6,
        gorduras_100g: 0.2,
        fibras_100g: 4.1,
        sodio_100g: 9,
        porcao_comum_g: 150,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Inhame cozido sem sal",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.EMAGRECIMENTO],
        indice_saciedade: "alto",
        observacoes: "Alimento funcional. Mucilagens que favorecem a microbiota intestinal.",
    },
    {
        id: "cc_013",
        nome: "Mandioca/Aipim Cozido",
        marca: "Geral",
        categoria: categorias.TUBERCULOS,
        imagem: "https://images.unsplash.com/photo-1598515213692-f47c6cd29da6?w=400&q=80",
        calorias_100g: 158,
        proteinas_100g: 1.0,
        carboidratos_100g: 38.1,
        gorduras_100g: 0.3,
        fibras_100g: 1.9,
        sodio_100g: 14,
        porcao_comum_g: 100,
        unidade_medida: "g",
        indice_glicemico: "alto",
        descricao: "Mandioca cozida",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Fonte calórica densa. Boa no pós-treino para ganho de massa.",
    },
];

// ============================================================
// LEGUMINOSAS
// ============================================================
const leguminosas = [
    {
        id: "lg_001",
        nome: "Feijão Carioca Cozido",
        marca: "Geral",
        categoria: categorias.LEGUMINOSAS,
        imagem: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=400&q=80",
        calorias_100g: 76,
        proteinas_100g: 4.8,
        carboidratos_100g: 13.6,
        gorduras_100g: 0.5,
        fibras_100g: 7.0,
        sodio_100g: 2,
        porcao_comum_g: 86,
        unidade_medida: "concha",
        peso_unidade_g: 86,
        descricao: "Feijão carioca cozido (1 concha = 86g)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.MANUTENCAO],
        indice_saciedade: "muito_alto",
        observacoes: "Alimento funcional. Dupla arroz+feijão forma proteína completa.",
    },
    {
        id: "lg_002",
        nome: "Feijão Preto Cozido",
        marca: "Geral",
        categoria: categorias.LEGUMINOSAS,
        imagem: "https://images.unsplash.com/photo-1619216893928-3b6428f2b0ec?w=400&q=80",
        calorias_100g: 77,
        proteinas_100g: 5.0,
        carboidratos_100g: 14.0,
        gorduras_100g: 0.5,
        fibras_100g: 8.7,
        sodio_100g: 1,
        porcao_comum_g: 86,
        unidade_medida: "concha",
        peso_unidade_g: 86,
        descricao: "Feijão preto cozido",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "muito_alto",
        observacoes: "Mais antioxidantes que o carioca (antocianinas). Rico em ferro.",
    },
    {
        id: "lg_003",
        nome: "Lentilha Cozida",
        marca: "Geral",
        categoria: categorias.LEGUMINOSAS,
        imagem: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400&q=80",
        calorias_100g: 116,
        proteinas_100g: 9.0,
        carboidratos_100g: 20.1,
        gorduras_100g: 0.4,
        fibras_100g: 7.9,
        sodio_100g: 2,
        porcao_comum_g: 100,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Lentilha cozida",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "muito_alto",
        observacoes: "Uma das leguminosas mais proteicas e com menor IG. Rica em folato e ferro.",
    },
    {
        id: "lg_004",
        nome: "Grão-de-Bico Cozido",
        marca: "Geral",
        categoria: categorias.LEGUMINOSAS,
        imagem: "https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400&q=80",
        calorias_100g: 164,
        proteinas_100g: 8.9,
        carboidratos_100g: 27.4,
        gorduras_100g: 2.6,
        fibras_100g: 7.6,
        sodio_100g: 7,
        porcao_comum_g: 100,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Grão-de-bico cozido",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.MANUTENCAO],
        indice_saciedade: "muito_alto",
        observacoes: "Excelente para dietas plant-based. Rico em zinco e manganês.",
    },
    {
        id: "lg_005",
        nome: "Edamame (soja verde cozida)",
        marca: "Geral",
        categoria: categorias.LEGUMINOSAS,
        imagem: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80",
        calorias_100g: 122,
        proteinas_100g: 11.9,
        carboidratos_100g: 8.9,
        gorduras_100g: 5.2,
        fibras_100g: 5.2,
        sodio_100g: 6,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Soja verde (edamame) cozida sem sal",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Proteína completa de origem vegetal. Rica em isoflavonas e vitamina K.",
    },
];

// ============================================================
// PROTEÍNAS VEGETAIS
// ============================================================
const proteinasVegetais = [
    {
        id: "pv_001",
        nome: "Tofu Firme",
        marca: "Geral",
        categoria: categorias.PROTEINAS_VEGETAIS,
        imagem: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",
        calorias_100g: 76,
        proteinas_100g: 8.1,
        carboidratos_100g: 1.9,
        gorduras_100g: 4.2,
        fibras_100g: 0.3,
        sodio_100g: 7,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Tofu firme natural",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Proteína completa vegetal. Absorve temperos com facilidade.",
    },
    {
        id: "pv_002",
        nome: "Tempeh",
        marca: "Geral",
        categoria: categorias.PROTEINAS_VEGETAIS,
        imagem: "https://images.unsplash.com/photo-1604155350033-ccd1f6a9032f?w=400&q=80",
        calorias_100g: 193,
        proteinas_100g: 19.9,
        carboidratos_100g: 9.4,
        gorduras_100g: 10.8,
        fibras_100g: 5.0,
        sodio_100g: 9,
        porcao_comum_g: 80,
        unidade_medida: "g",
        descricao: "Tempeh de soja fermentado",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "Mais proteico que o tofu. Fermentado: melhora absorção de nutrientes.",
    },
];

// ============================================================
// FRUTAS
// ============================================================
const frutas = [
    {
        id: "fr_001",
        nome: "Banana Prata",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400&q=80",
        calorias_100g: 89,
        proteinas_100g: 1.1,
        carboidratos_100g: 22.8,
        gorduras_100g: 0.3,
        fibras_100g: 2.0,
        sodio_100g: 1,
        porcao_comum_g: 87,
        unidade_medida: "unidade",
        peso_unidade_g: 87,
        indice_glicemico: "medio",
        descricao: "Banana prata madura (1 unidade média ≈ 87g)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.MANUTENCAO],
        indice_saciedade: "medio",
        observacoes: "Boa fonte de potássio e vitamina B6. Excelente pré-treino.",
    },
    {
        id: "fr_002",
        nome: "Maçã Fuji",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80",
        calorias_100g: 52,
        proteinas_100g: 0.3,
        carboidratos_100g: 13.8,
        gorduras_100g: 0.2,
        fibras_100g: 2.4,
        sodio_100g: 1,
        porcao_comum_g: 138,
        unidade_medida: "unidade",
        peso_unidade_g: 138,
        indice_glicemico: "baixo",
        descricao: "Maçã Fuji com casca (1 unidade média ≈ 138g)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "Rica em pectina (fibra solúvel). Sempre comer com casca para mais fibras.",
    },
    {
        id: "fr_003",
        nome: "Morango",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80",
        calorias_100g: 32,
        proteinas_100g: 0.7,
        carboidratos_100g: 7.7,
        gorduras_100g: 0.3,
        fibras_100g: 2.0,
        sodio_100g: 1,
        porcao_comum_g: 150,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Morangos frescos",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Baixíssimo calórico. Riquíssimo em vitamina C e antioxidantes.",
    },
    {
        id: "fr_004",
        nome: "Mirtilo / Blueberry",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&q=80",
        calorias_100g: 57,
        proteinas_100g: 0.7,
        carboidratos_100g: 14.5,
        gorduras_100g: 0.3,
        fibras_100g: 2.4,
        sodio_100g: 1,
        porcao_comum_g: 100,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Mirtilos frescos ou congelados",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Fruta com maior concentração de antioxidantes. Neuroprotegente.",
    },
    {
        id: "fr_005",
        nome: "Abacate",
        marca: "Geral",
        categoria: categorias.GORDURAS_BOAS,
        imagem: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80",
        calorias_100g: 160,
        proteinas_100g: 2.0,
        carboidratos_100g: 8.5,
        gorduras_100g: 14.7,
        fibras_100g: 6.7,
        sodio_100g: 7,
        porcao_comum_g: 80,
        unidade_medida: "g",
        indice_glicemico: "baixo",
        descricao: "Abacate Hass maduro (½ unidade pequena ≈ 80g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.DEFINICAO, objetivos.EMAGRECIMENTO],
        indice_saciedade: "muito_alto",
        observacoes: "Rico em ácido oleico (ômega-9), potássio e vitamina E.",
    },
    {
        id: "fr_006",
        nome: "Melancia",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80",
        calorias_100g: 30,
        proteinas_100g: 0.6,
        carboidratos_100g: 7.6,
        gorduras_100g: 0.2,
        fibras_100g: 0.4,
        sodio_100g: 1,
        porcao_comum_g: 200,
        unidade_medida: "g",
        indice_glicemico: "alto",
        descricao: "Melancia sem casca",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "baixo",
        observacoes: "Baixíssima caloria e alta hidratação. Rica em citrulina.",
    },
    {
        id: "fr_007",
        nome: "Kiwi",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=400&q=80",
        calorias_100g: 61,
        proteinas_100g: 1.1,
        carboidratos_100g: 14.7,
        gorduras_100g: 0.5,
        fibras_100g: 3.0,
        sodio_100g: 3,
        porcao_comum_g: 69,
        unidade_medida: "unidade",
        peso_unidade_g: 69,
        indice_glicemico: "baixo",
        descricao: "Kiwi verde (1 unidade ≈ 69g)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Uma das frutas com maior teor de vitamina C. Melhora sono e digestão.",
    },
    {
        id: "fr_008",
        nome: "Laranja Pera",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80",
        calorias_100g: 47,
        proteinas_100g: 1.0,
        carboidratos_100g: 11.7,
        gorduras_100g: 0.1,
        fibras_100g: 2.4,
        sodio_100g: 1,
        porcao_comum_g: 180,
        unidade_medida: "unidade",
        peso_unidade_g: 180,
        indice_glicemico: "baixo",
        descricao: "Laranja pera madura",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Rica em vitamina C, flavonoides e hesperidina. Preferir a fruta ao suco.",
    },
    {
        id: "fr_009",
        nome: "Manga Tommy",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80",
        calorias_100g: 60,
        proteinas_100g: 0.8,
        carboidratos_100g: 15.0,
        gorduras_100g: 0.4,
        fibras_100g: 1.6,
        sodio_100g: 2,
        porcao_comum_g: 100,
        unidade_medida: "g",
        indice_glicemico: "medio",
        descricao: "Manga tommy madura",
        objetivos_recomendados: [objetivos.MANUTENCAO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Rica em betacaroteno e vitamina C. Consumir com moderação no emagrecimento.",
    },
    {
        id: "fr_010",
        nome: "Mamão Papaia",
        marca: "Geral",
        categoria: categorias.FRUTAS,
        imagem: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&q=80",
        calorias_100g: 43,
        proteinas_100g: 0.5,
        carboidratos_100g: 10.8,
        gorduras_100g: 0.1,
        fibras_100g: 1.7,
        sodio_100g: 8,
        porcao_comum_g: 200,
        unidade_medida: "fatia",
        peso_unidade_g: 200,
        indice_glicemico: "medio",
        descricao: "Mamão papaia maduro (1 fatia média ≈ 200g)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Rica em papaína (enzima digestiva) e vitamina C. Excelente para digestão.",
    },
];

// ============================================================
// LEGUMES E VERDURAS
// ============================================================
const legumesVerduras = [
    {
        id: "lv_001",
        nome: "Brócolis Cozido",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400&q=80",
        calorias_100g: 35,
        proteinas_100g: 2.4,
        carboidratos_100g: 7.2,
        gorduras_100g: 0.4,
        fibras_100g: 2.6,
        sodio_100g: 33,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Brócolis cozido no vapor ou água",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Crucífera: sulforafano com propriedades anticâncer. Rica em vitamina C e K.",
    },
    {
        id: "lv_002",
        nome: "Espinafre Cru",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
        calorias_100g: 23,
        proteinas_100g: 2.9,
        carboidratos_100g: 3.6,
        gorduras_100g: 0.4,
        fibras_100g: 2.2,
        sodio_100g: 79,
        porcao_comum_g: 30,
        unidade_medida: "g",
        descricao: "Folhas frescas de espinafre",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Rica em ferro, cálcio e vitamina K. Vitamina C melhora absorção do ferro.",
    },
    {
        id: "lv_003",
        nome: "Abobrinha Cozida",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80",
        calorias_100g: 17,
        proteinas_100g: 1.2,
        carboidratos_100g: 3.1,
        gorduras_100g: 0.3,
        fibras_100g: 1.0,
        sodio_100g: 3,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Abobrinha italiana cozida",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Extremamente baixo calórico. Aumenta volume das refeições sem calorias.",
    },
    {
        id: "lv_004",
        nome: "Tomate",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=400&q=80",
        calorias_100g: 18,
        proteinas_100g: 0.9,
        carboidratos_100g: 3.9,
        gorduras_100g: 0.2,
        fibras_100g: 1.2,
        sodio_100g: 5,
        porcao_comum_g: 90,
        unidade_medida: "unidade",
        peso_unidade_g: 90,
        descricao: "Tomate maduro",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "baixo",
        observacoes: "Rico em licopeno (antioxidante). Absorção aumenta com cozimento e azeite.",
    },
    {
        id: "lv_005",
        nome: "Cenoura Crua",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80",
        calorias_100g: 34,
        proteinas_100g: 0.9,
        carboidratos_100g: 7.9,
        gorduras_100g: 0.2,
        fibras_100g: 2.8,
        sodio_100g: 69,
        porcao_comum_g: 60,
        unidade_medida: "unidade",
        peso_unidade_g: 60,
        descricao: "Cenoura crua com casca",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Rica em betacaroteno (pró-vitamina A). Boa opção de snack.",
    },
    {
        id: "lv_006",
        nome: "Couve-Flor Cozida",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400&q=80",
        calorias_100g: 25,
        proteinas_100g: 1.9,
        carboidratos_100g: 4.9,
        gorduras_100g: 0.3,
        fibras_100g: 2.0,
        sodio_100g: 30,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Couve-flor cozida no vapor",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "Crucífera anti-inflamatória. Substituta do arroz e batata em low-carb.",
    },
    {
        id: "lv_007",
        nome: "Pepino Japonês",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&q=80",
        calorias_100g: 15,
        proteinas_100g: 0.7,
        carboidratos_100g: 3.6,
        gorduras_100g: 0.1,
        fibras_100g: 0.5,
        sodio_100g: 2,
        porcao_comum_g: 100,
        unidade_medida: "g",
        descricao: "Pepino japonês com casca",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "baixo",
        observacoes: "95% água. Praticamente zero caloria. Hidratante.",
    },
    {
        id: "lv_008",
        nome: "Alface Crespa",
        marca: "Geral",
        categoria: categorias.LEGUMES_VERDURAS,
        imagem: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&q=80",
        calorias_100g: 15,
        proteinas_100g: 1.4,
        carboidratos_100g: 2.2,
        gorduras_100g: 0.2,
        fibras_100g: 1.8,
        sodio_100g: 10,
        porcao_comum_g: 30,
        unidade_medida: "g",
        descricao: "Folhas frescas de alface crespa",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "baixo",
        observacoes: "Base de saladas. Praticamente zero calorias.",
    },
];

// ============================================================
// GORDURAS SAUDÁVEIS
// ============================================================
const gordurasSaudaveis = [
    {
        id: "gs_001",
        nome: "Azeite de Oliva Extra Virgem",
        marca: "Geral",
        categoria: categorias.GORDURAS_BOAS,
        imagem: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80",
        calorias_100g: 884,
        proteinas_100g: 0.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 100.0,
        fibras_100g: 0.0,
        sodio_100g: 0,
        porcao_comum_g: 10,
        unidade_medida: "colher_sopa",
        peso_unidade_g: 10,
        descricao: "Extra virgem prensado a frio (1 colher sopa = 10g = 88 kcal)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Rico em polifenóis e ácido oleico. Use frio ou em baixa temperatura.",
    },
    {
        id: "gs_002",
        nome: "Manteiga Integral",
        marca: "Geral",
        categoria: categorias.GORDURAS_BOAS,
        imagem: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&q=80",
        calorias_100g: 717,
        proteinas_100g: 0.9,
        carboidratos_100g: 0.1,
        gorduras_100g: 81.1,
        fibras_100g: 0.0,
        sodio_100g: 11,
        porcao_comum_g: 10,
        unidade_medida: "colher_chá",
        peso_unidade_g: 10,
        descricao: "Manteiga sem sal (1 colher chá = 10g = 72 kcal)",
        objetivos_recomendados: [objetivos.MANUTENCAO, objetivos.GANHO_MASSA],
        indice_saciedade: "medio",
        observacoes: "Usar com moderação. Preferir versão sem sal de vaca criada a pasto.",
    },
    {
        id: "gs_003",
        nome: "Óleo de Coco Virgem",
        marca: "Geral",
        categoria: categorias.GORDURAS_BOAS,
        imagem: "https://images.unsplash.com/photo-1595351298020-038700609878?w=400&q=80",
        calorias_100g: 862,
        proteinas_100g: 0.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 100.0,
        fibras_100g: 0.0,
        sodio_100g: 0,
        porcao_comum_g: 10,
        unidade_medida: "colher_sopa",
        peso_unidade_g: 10,
        descricao: "Óleo de coco virgem prensado a frio (1 colher sopa = 10g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL],
        indice_saciedade: "medio",
        observacoes: "Rico em TCM (triglicerídeos de cadeia média). Use com moderação.",
    },
];

// ============================================================
// OLEAGINOSAS E SEMENTES
// ============================================================
const oleaginosas = [
    {
        id: "ol_001",
        nome: "Amendoim Torrado (sem sal)",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1567892737950-30c4db37e6e3?w=400&q=80",
        calorias_100g: 567,
        proteinas_100g: 25.8,
        carboidratos_100g: 16.1,
        gorduras_100g: 49.2,
        fibras_100g: 8.5,
        sodio_100g: 18,
        porcao_comum_g: 30,
        unidade_medida: "g",
        descricao: "Amendoim torrado sem sal (1 punhado ≈ 30g)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.SAUDE_GERAL],
        indice_saciedade: "muito_alto",
        observacoes: "Alto calórico mas nutritivo. Boa fonte de proteína vegetal e resveratrol.",
    },
    {
        id: "ol_002",
        nome: "Pasta de Amendoim Integral",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1590080875249-7a3e90f0c7b3?w=400&q=80",
        calorias_100g: 589,
        proteinas_100g: 25.0,
        carboidratos_100g: 20.0,
        gorduras_100g: 50.0,
        fibras_100g: 6.0,
        sodio_100g: 15,
        porcao_comum_g: 30,
        unidade_medida: "colher_sopa",
        peso_unidade_g: 30,
        descricao: "Pasta integral, ingrediente único: amendoim (1 colher sopa cheia = 30g)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.SAUDE_GERAL],
        indice_saciedade: "muito_alto",
        observacoes: "Verificar rótulo: ingrediente único. Evitar versões com açúcar.",
    },
    {
        id: "ol_003",
        nome: "Castanha do Pará",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400&q=80",
        calorias_100g: 656,
        proteinas_100g: 14.3,
        carboidratos_100g: 12.3,
        gorduras_100g: 66.4,
        fibras_100g: 7.5,
        sodio_100g: 3,
        porcao_comum_g: 10,
        unidade_medida: "unidade",
        peso_unidade_g: 10,
        descricao: "Castanha do Pará crua (1 unidade ≈ 10g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL],
        indice_saciedade: "alto",
        observacoes: "1 unidade/dia supre 100% da necessidade diária de selênio.",
    },
    {
        id: "ol_004",
        nome: "Nozes",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1448907503123-67254d59ca4f?w=400&q=80",
        calorias_100g: 654,
        proteinas_100g: 15.2,
        carboidratos_100g: 13.7,
        gorduras_100g: 65.2,
        fibras_100g: 6.7,
        sodio_100g: 2,
        porcao_comum_g: 30,
        unidade_medida: "g",
        descricao: "Nozes cruas (4–5 unidades ≈ 30g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.DEFINICAO],
        indice_saciedade: "muito_alto",
        observacoes: "Maior fonte vegetal de ômega-3 (ALA). Neuroprotetor comprovado.",
    },
    {
        id: "ol_005",
        nome: "Amêndoas",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1508747703725-719777637510?w=400&q=80",
        calorias_100g: 579,
        proteinas_100g: 21.2,
        carboidratos_100g: 21.6,
        gorduras_100g: 49.9,
        fibras_100g: 12.5,
        sodio_100g: 1,
        porcao_comum_g: 30,
        unidade_medida: "g",
        descricao: "Amêndoas cruas (20–25 unidades ≈ 30g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.EMAGRECIMENTO],
        indice_saciedade: "muito_alto",
        observacoes: "Rica em vitamina E, magnésio e cálcio.",
    },
    {
        id: "ol_006",
        nome: "Chia",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1518596958855-67e71b011748?w=400&q=80",
        calorias_100g: 486,
        proteinas_100g: 16.5,
        carboidratos_100g: 42.1,
        gorduras_100g: 30.7,
        fibras_100g: 34.4,
        sodio_100g: 16,
        porcao_comum_g: 15,
        unidade_medida: "colher_sopa",
        peso_unidade_g: 15,
        descricao: "Sementes de chia (1 colher sopa = 15g)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "muito_alto",
        observacoes: "Altíssimo teor de fibras e ômega-3. Hidrate antes de consumir.",
    },
    {
        id: "ol_007",
        nome: "Linhaça Dourada",
        marca: "Geral",
        categoria: categorias.OLEAGINOSAS,
        imagem: "https://images.unsplash.com/photo-1614531341773-3bff8b7cb3fc?w=400&q=80",
        calorias_100g: 534,
        proteinas_100g: 18.3,
        carboidratos_100g: 28.9,
        gorduras_100g: 42.2,
        fibras_100g: 27.3,
        sodio_100g: 30,
        porcao_comum_g: 15,
        unidade_medida: "colher_sopa",
        peso_unidade_g: 15,
        descricao: "Sementes de linhaça dourada (1 colher sopa = 15g)",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.EMAGRECIMENTO],
        indice_saciedade: "alto",
        observacoes: "Rica em lignanas e ômega-3. Consumir sempre moída para absorção.",
    },
];

// ============================================================
// SUPLEMENTOS
// ============================================================
const suplementos = [
    {
        id: "sp_001",
        nome: "Whey Protein Concentrado",
        marca: "Growth Supplements (Aprox.)",
        categoria: categorias.SUPLEMENTOS,
        imagem: "https://images.unsplash.com/photo-1598720431049-98e5b9b47b51?w=400&q=80",
        calorias_100g: 400,
        proteinas_100g: 80.0,
        carboidratos_100g: 10.0,
        gorduras_100g: 5.0,
        fibras_100g: 0.0,
        sodio_100g: 200,
        porcao_comum_g: 30,
        unidade_medida: "scoop",
        peso_unidade_g: 30,
        descricao: "Whey concentrado (1 scoop ≈ 30g = ~24g proteína)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Pós-treino principal. Verificar selos de qualidade (Informed Sport, NSF).",
    },
    {
        id: "sp_002",
        nome: "Whey Protein Isolado",
        marca: "Geral",
        categoria: categorias.SUPLEMENTOS,
        imagem: "https://images.unsplash.com/photo-1579722820308-d74e571900a9?w=400&q=80",
        calorias_100g: 370,
        proteinas_100g: 90.0,
        carboidratos_100g: 2.0,
        gorduras_100g: 1.5,
        fibras_100g: 0.0,
        sodio_100g: 160,
        porcao_comum_g: 30,
        unidade_medida: "scoop",
        peso_unidade_g: 30,
        descricao: "Whey isolado (1 scoop ≈ 30g = ~27g proteína)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO],
        indice_saciedade: "medio",
        observacoes: "Menor teor de lactose e gordura. Indicado para intolerantes ou em cutting.",
    },
    {
        id: "sp_003",
        nome: "Caseína (Proteína Micelar)",
        marca: "Geral",
        categoria: categorias.SUPLEMENTOS,
        imagem: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80",
        calorias_100g: 380,
        proteinas_100g: 83.0,
        carboidratos_100g: 5.0,
        gorduras_100g: 2.0,
        fibras_100g: 0.0,
        sodio_100g: 350,
        porcao_comum_g: 35,
        unidade_medida: "scoop",
        peso_unidade_g: 35,
        descricao: "Proteína de digestão lenta (1 scoop ≈ 35g)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "muito_alto",
        observacoes: "Ideal antes de dormir. Digestão lenta mantém aminoácidos por 7-8h.",
    },
    {
        id: "sp_004",
        nome: "Proteína Vegana (Ervilha + Arroz)",
        marca: "Geral",
        categoria: categorias.SUPLEMENTOS,
        imagem: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
        calorias_100g: 390,
        proteinas_100g: 75.0,
        carboidratos_100g: 12.0,
        gorduras_100g: 6.0,
        fibras_100g: 3.0,
        sodio_100g: 480,
        porcao_comum_g: 35,
        unidade_medida: "scoop",
        peso_unidade_g: 35,
        descricao: "Blend de proteína de ervilha e arroz (1 scoop ≈ 35g)",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "alto",
        observacoes: "Proteína completa para veganos. Combinação forma todos aminoácidos essenciais.",
    },
    {
        id: "sp_005",
        nome: "Creatina Monohidratada",
        marca: "Geral",
        categoria: categorias.SUPLEMENTOS,
        imagem: "https://images.unsplash.com/photo-1617196034450-b5f03a5b01b1?w=400&q=80",
        calorias_100g: 0,
        proteinas_100g: 0.0,
        carboidratos_100g: 0.0,
        gorduras_100g: 0.0,
        fibras_100g: 0.0,
        sodio_100g: 0,
        porcao_comum_g: 5,
        unidade_medida: "colher_chá",
        peso_unidade_g: 5,
        descricao: "Dose diária = 3-5g",
        objetivos_recomendados: [objetivos.GANHO_MASSA, objetivos.DEFINICAO],
        indice_saciedade: "nenhum",
        observacoes: "Suplemento mais estudado do mundo. Melhora força, potência e hipertrofia.",
    },
    {
        id: "sp_006",
        nome: "Albumina em Pó",
        marca: "Geral",
        categoria: categorias.SUPLEMENTOS,
        imagem: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400&q=80",
        calorias_100g: 380,
        proteinas_100g: 80.0,
        carboidratos_100g: 4.0,
        gorduras_100g: 1.0,
        fibras_100g: 0.0,
        sodio_100g: 900,
        porcao_comum_g: 25,
        unidade_medida: "scoop",
        peso_unidade_g: 25,
        descricao: "Clara de ovo desidratada em pó (1 scoop ≈ 25g)",
        objetivos_recomendados: [objetivos.DEFINICAO, objetivos.EMAGRECIMENTO],
        indice_saciedade: "alto",
        observacoes: "Digestão intermediária. Alto sódio: atenção na dieta hipossódica.",
    },
];

// ============================================================
// BEBIDAS
// ============================================================
const bebidas = [
    {
        id: "bv_001",
        nome: "Café Preto sem Açúcar",
        marca: "Geral",
        categoria: categorias.BEBIDAS,
        imagem: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",
        calorias_100g: 2,
        proteinas_100g: 0.3,
        carboidratos_100g: 0.0,
        gorduras_100g: 0.0,
        fibras_100g: 0.0,
        sodio_100g: 2,
        porcao_comum_g: 200,
        unidade_medida: "ml",
        descricao: "Café coado ou expresso sem açúcar",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.DEFINICAO, objetivos.SAUDE_GERAL],
        indice_saciedade: "baixo",
        observacoes: "Cafeína aumenta metabolismo e melhora performance. Rico em antioxidantes.",
    },
    {
        id: "bv_002",
        nome: "Chá Verde",
        marca: "Geral",
        categoria: categorias.BEBIDAS,
        imagem: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
        calorias_100g: 1,
        proteinas_100g: 0.0,
        carboidratos_100g: 0.2,
        gorduras_100g: 0.0,
        fibras_100g: 0.0,
        sodio_100g: 1,
        porcao_comum_g: 240,
        unidade_medida: "ml",
        descricao: "Chá verde infusionado (sem açúcar)",
        objetivos_recomendados: [objetivos.EMAGRECIMENTO, objetivos.SAUDE_GERAL],
        indice_saciedade: "baixo",
        observacoes: "Rico em EGCG (catequinas). Efeito termogênico e antioxidante.",
    },
    {
        id: "bv_003",
        nome: "Água de Coco Natural",
        marca: "Geral",
        categoria: categorias.BEBIDAS,
        imagem: "https://images.unsplash.com/photo-1536494126589-29fadf0d7e3c?w=400&q=80",
        calorias_100g: 19,
        proteinas_100g: 0.7,
        carboidratos_100g: 3.7,
        gorduras_100g: 0.2,
        fibras_100g: 1.1,
        sodio_100g: 105,
        porcao_comum_g: 300,
        unidade_medida: "ml",
        descricao: "Água de coco verde in natura",
        objetivos_recomendados: [objetivos.SAUDE_GERAL, objetivos.MANUTENCAO],
        indice_saciedade: "baixo",
        observacoes: "Excelente repositor de eletrólitos (potássio e sódio) pós-treino.",
    },
];

// ============================================================
// EXPORTAÇÃO CONSOLIDADA
// ============================================================

export const alimentosCompletos = [
    ...proteinasAnimais,
    ...ovos,
    ...laticinios,
    ...leguminosas,
    ...proteinasVegetais,
    ...carboidratosComplexos,
    ...frutas,
    ...legumesVerduras,
    ...gordurasSaudaveis,
    ...oleaginosas,
    ...suplementos,
    ...bebidas,
];

// ============================================================
// UTILITÁRIOS
// ============================================================

/**
 * Filtra alimentos por objetivo nutricional
 * @param {string} objetivo - Use valores de objetivos.*
 * @returns {Array} Lista de alimentos filtrados
 */
export const filtrarPorObjetivo = (objetivo) =>
    alimentosCompletos.filter((a) =>
        a.objetivos_recomendados.includes(objetivo)
    );

/**
 * Filtra alimentos por categoria
 * @param {string} categoria - Use valores de categorias.*
 */
export const filtrarPorCategoria = (categoria) =>
    alimentosCompletos.filter((a) => a.categoria === categoria);

/**
 * Calcula macronutrientes para uma quantidade específica em gramas
 * @param {object} alimento - Objeto do alimento
 * @param {number} gramas - Quantidade consumida em gramas
 */
export const calcularMacrosPorPorcao = (alimento, gramas) => {
    const fator = gramas / 100;
    return {
        nome: alimento.nome,
        gramas,
        calorias: +(alimento.calorias_100g * fator).toFixed(1),
        proteinas: +(alimento.proteinas_100g * fator).toFixed(1),
        carboidratos: +(alimento.carboidratos_100g * fator).toFixed(1),
        gorduras: +(alimento.gorduras_100g * fator).toFixed(1),
        fibras: +((alimento.fibras_100g || 0) * fator).toFixed(1),
    };
};

/**
 * Busca alimentos por nome (busca parcial)
 * @param {string} termo - Texto de busca
 */
export const buscarAlimento = (termo) =>
    alimentosCompletos.filter((a) =>
        a.nome.toLowerCase().includes(termo.toLowerCase())
    );

export default alimentosCompletos;
